//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingClub.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistrations
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int EventId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Events Events { get; set; }
    }
}
