//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingClub.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItems
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string SizeOrWeight { get; set; }
        public int StatusId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual InventoryStatuses InventoryStatuses { get; set; }
    }
}
